---
- name: Backup PostgreSQL Databases
  hosts: all
  become: yes

  tasks:
    - name: Create backup directory
      file:
        path: /var/lib/postgresql/backup
        state: directory

    - name: Backup PostgreSQL databases
      become_user: postgres
      shell: pg_dumpall > /var/lib/postgresql/backup/all_databases_backup.sql
